Repository openfga/openfga, pull requests merged in 2023-12, with the labels that each got.

#1200 fix: handle floating point conversion errors
  assets/tests/abac_tests.yaml
  internal/condition/types/converters.go
Labels: abac

#1193 docs(godoc): add package doc to `graph` package
  internal/graph/graph.go
Labels: Stale

#1261 docs: update encoder package documentation
  pkg/encoder/base64.go
  pkg/encoder/doc.go
  pkg/encoder/encoder.go
  pkg/encoder/token_encoder.go
Labels: documentation
