Repository openfga/openfga, pull requests merged in 2024-09, with the labels that each got.

#1899 ci: add permissions block to changelog enforcement
  .github/workflows/enforce-changelog-entry.yaml
Labels: Skip-Changelog

#1896 test: add an intersection test for TypeSystem
  pkg/typesystem/typesystem_create_test.go
Labels: tests

#1912 ci: reorganize 'main' workflow and delete unused workflow
  .github/workflows/codecov.yaml
  .github/workflows/load-test.yaml
  .github/workflows/main.yaml
Labels: Skip-Changelog

#1917 refactor: remove unused `emptyTupleIterator
  pkg/storage/iterators.go
  pkg/storage/iterators_test.go
Labels: Skip-Changelog

#1922 refactor: remove unused channels in SQL iterators
  pkg/storage/sqlcommon/sqlcommon.go
  pkg/storage/sqlite/tuple_iterator.go
Labels: Skip-Changelog

#1929 extend list users test timeout
  tests/listusers/listusers_test.go
Labels: Skip-Changelog

#1934 chore: add trace for consumeUsersets and produceUsersets
  internal/graph/check.go
Labels: Skip-Changelog

#1947 docs: Remove specific Go version in README.md
  README.md
Labels: Skip-Changelog

#1937 fix: add check for oidc set as authn method
  cmd/run/run.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: Skip-Changelog

#1943 chore: use backend-specific HandleSQLError implementations
  pkg/storage/mysql/mysql.go
  pkg/storage/mysql/mysql_test.go
  pkg/storage/postgres/postgres.go
  pkg/storage/postgres/postgres_test.go
  pkg/storage/sqlcommon/sqlcommon.go
  pkg/storage/sqlcommon/sqlcommon_test.go
Labels: Skip-Changelog

#1946 chore: identify recursive userset model that can be optimized
  go.mod
  go.sum
  internal/checkutil/checkutil_test.go
  internal/graph/cached_resolver_test.go
  internal/graph/check_test.go
  internal/graph/graph_test.go
  internal/validation/validation_test.go
  pkg/server/commands/listusers/list_users_rpc_test.go
  pkg/server/commands/reverseexpand/reverse_expand_test.go
  pkg/server/commands/write.go
  pkg/server/commands/write_assertions.go
  pkg/server/test/list_objects.go
  pkg/server/test/reverse_expand.go
  pkg/typesystem/typesystem.go
  pkg/typesystem/typesystem_create_test.go
  pkg/typesystem/typesystem_test.go
Labels: Skip-Changelog

#1939 chore: Unify shell run blocks in README.md
  README.md
Labels: documentation, Skip-Changelog

#1914 feat: access control modules
  internal/authz/authz.go
  internal/authz/authz_test.go
  pkg/server/server.go
  pkg/server/server_authz_test.go
Labels: Skip-Changelog

#1954 feat: identify model optimizable for recursive ttu
  go.mod
  go.sum
  pkg/typesystem/typesystem.go
  pkg/typesystem/typesystem_test.go
Labels: Skip-Changelog

#1953 chore: reduce diffs between storage implementations
  pkg/storage/mysql/mysql.go
  pkg/storage/mysql/mysql_test.go
  pkg/storage/postgres/postgres.go
  pkg/storage/postgres/postgres_test.go
  pkg/storage/sqlcommon/sqlcommon.go
  pkg/storage/sqlite/sqlite.go
Labels: Skip-Changelog

#1972 Minor perf improvements for fast path
  internal/checkutil/checkutil.go
  internal/checkutil/checkutil_test.go
  internal/graph/check.go
  pkg/typesystem/typesystem.go
  pkg/typesystem/typesystem_create_test.go
  pkg/typesystem/typesystem_test.go
Labels: performance, Skip-Changelog
