Repository openfga/openfga, pull requests merged in 2024-10, with the labels that each got.

#1974 fix: combinedIterator must stop all iterators
  pkg/storage/iterators.go
  pkg/storage/iterators_test.go
Labels: performance, Skip-Changelog

#1975 chore: run matrix memory tests once
  tests/check/check_test.go
Labels: Skip-Changelog

#1977 fix: close cache once
  pkg/storage/cache.go
  pkg/storage/cache_test.go
Labels: Skip-Changelog

#1857 refactor: introduce Check command
  internal/graph/check.go
  internal/graph/interface.go
  internal/graph/mock_check_resolver.go
  pkg/server/commands/check_command.go
  pkg/server/commands/check_command_test.go
  pkg/server/server.go
  pkg/storage/storagewrappers/boundedconcurrency.go
  pkg/storage/storagewrappers/combinedtuplereader.go
Labels: Skip-Changelog

#1984 fix: faster tuple validation when reading from datastore
  internal/graph/check.go
  internal/validation/validation.go
  internal/validation/validation_test.go
  pkg/server/commands/check_command.go
  pkg/server/commands/list_objects.go
  pkg/server/commands/listusers/validate.go
  pkg/server/commands/reverseexpand/reverse_expand_test.go
  pkg/server/commands/write.go
  pkg/server/commands/write_assertions.go
  pkg/tuple/tuple.go
Labels: performance, Skip-Changelog

#1983 test: testing the return of func constructAuthorizationModelFromSQLRows
  pkg/storage/mysql/mysql_test.go
  pkg/storage/postgres/postgres_test.go
Labels: tests, Skip-Changelog

#1950 feat: add list stores authorization
  internal/authz/authz.go
  internal/authz/authz_test.go
  pkg/server/commands/list_stores.go
  pkg/server/server.go
  pkg/server/server_authz_test.go
  pkg/server/test/list_stores.go
  pkg/storage/memory/memory.go
  pkg/storage/mysql/mysql.go
  pkg/storage/postgres/postgres.go
  pkg/storage/sqlite/sqlite.go
  pkg/storage/storage.go
Labels: Skip-Changelog

#1994 fix: use proper link to contribution guidelines
  CONTRIBUTING.md
Labels: Skip-Changelog

#1996 test: add more Check benchmarks
  tests/check/check_test.go
Labels: Skip-Changelog

#1982 chore: refactor reflexive tuple/userset checker into separate functions
  internal/graph/check.go
  pkg/server/commands/listusers/list_users_rpc.go
  pkg/server/commands/reverseexpand/reverse_expand.go
  pkg/tuple/tuple.go
  pkg/tuple/tuple_test.go
Labels: Skip-Changelog

#2008 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Skip-Changelog

#1997 fix: remove flakeyness from TestCheckWithCachedIterator
  pkg/server/server_test.go
Labels: Skip-Changelog

#2001 docs: update NOTICE file
  NOTICE
Labels: Skip-Changelog

#1963 perf: optimize nested userset
  .config-schema.json
  CHANGELOG.md
  internal/graph/cached_resolver_test.go
  internal/graph/check.go
  internal/graph/check_test.go
  internal/mocks/mock_error_iterator.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/testutils/testutils.go
  tests/check/check.go
  tests/check/check_test.go
  tests/check/check_userset.go
  tests/functional_test.go
  tests/listobjects/listobjects_test.go
  tests/listusers/listusers_test.go
Labels: performance

#1992 refactor: improve flexibility of the filterTuples function
  pkg/storage/storagewrappers/combinedtuplereader.go
  pkg/storage/storagewrappers/combinedtuplereader_test.go
Labels: Skip-Changelog

#2010 chore: thread-safe `ResolveCheckRequest.Clone()`
  internal/graph/resolve_check_request.go
  internal/graph/resolve_check_request_test.go
Labels: Skip-Changelog

#2012 refactor: simplify lru cache implementation
  internal/cachecontroller/cache_controller.go
  internal/cachecontroller/cache_controller_test.go
  internal/graph/cached_resolver.go
  internal/graph/cached_resolver_test.go
  internal/graph/storagewrapper.go
  internal/graph/storagewrapper_test.go
  internal/mocks/mock_cache.go
  pkg/storage/cache.go
  pkg/storage/cache_test.go
  pkg/storage/storagewrappers/caching.go
  pkg/storage/storagewrappers/caching_test.go
  pkg/typesystem/resolver.go
Labels: Skip-Changelog

#2004 refactor: make optimize nested userset generic
  internal/graph/check.go
  internal/graph/check_test.go
  internal/graph/tuplemapper.go
  internal/graph/tuplemapper_test.go
Labels: Skip-Changelog

#2017 refactor: Speed up check benchmark tests
  pkg/server/test/check.go
  pkg/server/test/server.go
  tests/check/check_test.go
Labels: Skip-Changelog

#2018 fix: update histogram buckets to distinguish between 0 and 1
  internal/graph/storagewrapper.go
Labels: Skip-Changelog

#2024 refactor: speed up check benchmark tests part 2
  .github/workflows/main.yaml
  .github/workflows/pull_request.yaml
  pkg/server/test/check.go
  tests/check/check_test.go
Labels: Skip-Changelog

#2027 Use proper interfaces and cleanup some duplication work
  internal/checkutil/checkutil.go
  internal/checkutil/checkutil_test.go
  internal/graph/check.go
  internal/graph/tuplemapper.go
  pkg/storage/iterators.go
Labels: Skip-Changelog

#2028 fix: docker setup
  docker-compose.override.yaml
  telemetry/otel-collector-config.yaml
Labels: Skip-Changelog

#2031 refactor: check command execute params
  pkg/server/commands/check_command.go
  pkg/server/commands/check_command_test.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/server/test/check.go
Labels: Skip-Changelog

#2034 fix(test): Fix flaky test in ListObjects dispatch throttling
  pkg/server/commands/list_objects_test.go
Labels: Skip-Changelog

#2032 feat: nested fast path refactor
  CHANGELOG.md
  internal/graph/check.go
  internal/graph/check_test.go
  internal/graph/mock_check_resolver.go
  internal/graph/tuplemapper.go
  internal/graph/tuplemapper_test.go
  internal/mocks/mock_cache.go
  internal/mocks/mock_encoder.go
  internal/mocks/mock_storage.go
  internal/mocks/mock_throttler.go
  pkg/storage/iterators.go
  pkg/storage/sortedset.go
Labels: Skip-Changelog

#1998 refactor: split the validation to the server specific and binary
  internal/server/config/config.go
  internal/server/config/config_test.go
Labels: Skip-Changelog

#2033 fix: add check for skip authz to all authz check calls
  pkg/server/server.go
  pkg/server/server_authz_test.go
Labels: Skip-Changelog

#2041 fixed tests after including openfga/api#208
  tests/functional_test.go
Labels: tests, Skip-Changelog

#2042 test: only listen on localhost to avoid prompting for permission
  cmd/run/run_test.go
  internal/mocks/mock_oidc_server.go
  internal/mocks/mock_tracing_server.go
  pkg/testutils/testutils.go
  tests/tests.go
Labels: Skip-Changelog

#2044 refactor: consolidate check_command error handling
  pkg/server/commands/check_command.go
  pkg/server/commands/check_command_test.go
  pkg/server/commands/errors.go
  pkg/server/server.go
Labels: Skip-Changelog

#2052 fix: clone request to avoid data race
  internal/graph/check.go
Labels: Skip-Changelog

#2056 chore: bump grpc health probe
  Dockerfile.goreleaser
Labels: Skip-Changelog

#2055 tmp/ContinuationTokenSerializer
  cmd/run/run.go
  internal/mocks/mock_storage.go
  pkg/server/commands/read_changes.go
  pkg/server/commands/read_changes_test.go
  pkg/server/server.go
  pkg/storage/memory/memory.go
  pkg/storage/memory/memory_test.go
  pkg/storage/mysql/mysql.go
  pkg/storage/mysql/mysql_test.go
  pkg/storage/postgres/postgres.go
  pkg/storage/postgres/postgres_test.go
  pkg/storage/sqlcommon/sqlcommon.go
  pkg/storage/sqlite/sqlite.go
  pkg/storage/sqlite/sqlite_test.go
  pkg/storage/storage.go
  pkg/storage/test/storage.go
  pkg/storage/test/tuples.go
Labels: Skip-Changelog

#2060 chore: move check directly assignable function out to its own function
  internal/graph/check.go
  internal/graph/check_test.go
  pkg/typesystem/typesystem_test.go
Labels: Skip-Changelog

#2022 refactor: track datastore query count in datastore wrapper
  internal/graph/cached_resolver.go
  internal/graph/cached_resolver_test.go
  internal/graph/check.go
  internal/graph/check_test.go
  internal/graph/graph.go
  internal/graph/resolve_check_request.go
  internal/graph/resolve_check_request_test.go
  internal/graph/resolve_check_response.go
  internal/graph/resolve_check_response_test.go
  pkg/server/commands/check_command.go
  pkg/server/commands/check_command_test.go
  pkg/server/commands/list_objects.go
  pkg/server/commands/list_objects_test.go
  pkg/server/commands/listusers/list_users.go
  pkg/server/commands/listusers/list_users_rpc.go
  pkg/server/commands/listusers/list_users_rpc_test.go
  pkg/server/commands/reverseexpand/reverse_expand.go
  pkg/server/server.go
  pkg/server/test/reverse_expand.go
  pkg/storage/storagewrappers/combinedtuplereader.go
  pkg/storage/storagewrappers/instrumented.go
  pkg/storage/storagewrappers/instrumented_test.go
Labels: Skip-Changelog

#2061 refactor: resolve check response
  internal/graph/cached_resolver_test.go
  internal/graph/check.go
  internal/graph/check_test.go
  internal/graph/graph.go
  internal/graph/resolve_check_request.go
  internal/graph/resolve_check_response.go
  internal/graph/resolve_check_response_test.go
  pkg/server/commands/check_command.go
  pkg/server/commands/check_command_test.go
Labels: Skip-Changelog
