Repository openfga/openfga, pull requests merged in 2025-09, with the labels that each got.

#2682 create codeql.yml
  .github/workflows/codeql.yml
Labels: github_actions, Skip-Changelog

#2694 fix: in-memory condition context not checked correctly for write
  pkg/storage/memory/memory.go
  pkg/storage/test/tuples.go
Labels: Skip-Changelog

#2692 chore: batch statements for write
  pkg/storage/mysql/mysql_test.go
  pkg/storage/postgres/postgres_test.go
  pkg/storage/sqlcommon/sqlcommon.go
  pkg/storage/sqlite/sqlite.go
  pkg/storage/sqlite/sqlite_test.go
  pkg/storage/test/tuples.go
Labels: Skip-Changelog

#2724 release: update changelog for release `v1.10.2`
  CHANGELOG.md
Labels: release
