Repository openfga/openfga, pull requests merged in 2025-06, with the labels that each got.

#2476 Revert "chore(deps): bump the dependencies group with 10 updates (#2471)
  go.mod
  go.sum
Labels: Skip-Changelog

#2477 chore: bump grpc-health-probe from v0.4.37 to v0.4.38
  Dockerfile
  Dockerfile.goreleaser
Labels: Skip-Changelog

#2494 chore: bump dependency
  cmd/openfga/main_test.go
  go.mod
  go.sum
  pkg/testfixtures/storage/mysql.go
  pkg/testfixtures/storage/postgres.go
Labels: Skip-Changelog

#2478 performance: refactored the shared iterator and shared iterator datastore
  CHANGELOG.md
  pkg/storage/storagewrappers/request.go
  pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore.go
  pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore_test.go
Labels: performance

#2510 docs(v1.8.16): add v1.8.16 release notes to CHANGELOG
  CHANGELOG.md
Labels: Skip-Changelog

#2514 clean: Remove fanin code
  internal/iterator/fan_in.go
  internal/iterator/fan_in_test.go
Labels: Skip-Changelog

#2517 chore: bump mysql driver + grpc packages
  go.mod
  go.sum
Labels: Skip-Changelog

#2468 feat: add GetEdgesForListObjects to typesystem
  internal/utils/filter.go
  internal/utils/filter_test.go
  internal/utils/reduce.go
  internal/utils/reduce_test.go
  pkg/typesystem/typesystem.go
  pkg/typesystem/typesystem_test.go
Labels: Skip-Changelog

#2518 feat: typesystem edges for intersection and exclusion
  pkg/typesystem/typesystem.go
  pkg/typesystem/weighted_graph.go
  pkg/typesystem/weighted_graph_test.go
Labels: Skip-Changelog

#2527 fix: shared iterator metrics
  pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore.go
Labels: bug, Skip-Changelog

#2533 CICD: skip revive var-naming rule
  .golangci.yaml
Labels: Skip-Changelog
