Repository openfga/openfga, pull requests merged in 2025-05, with the labels that each got.

#2423 feat: config for shared iterator framework
  .config-schema.json
  cmd/run/flags.go
  cmd/run/run.go
  cmd/run/run_test.go
  internal/shared/shared.go
  pkg/server/config/cache_settings.go
  pkg/server/config/config.go
  pkg/server/server.go
  pkg/storage/storagewrappers/request.go
  pkg/storage/storagewrappers/request_test.go
Labels: Skip-Changelog

#2425 fix: stream fastpath, move sql to lazy queries
  .config-schema.json
  CHANGELOG.md
  internal/graph/check_fast_path.go
  internal/graph/check_fast_path_test.go
  internal/graph/check_test.go
  internal/graph/object_providers.go
  internal/graph/object_providers_test.go
  internal/iterator/fan_in.go
  internal/iterator/fan_in_test.go
  internal/iterator/stream.go
  internal/iterator/stream_test.go
  internal/mocks/mock_cache.go
  pkg/server/config/config.go
  pkg/server/server_test.go
  pkg/server/test/list_objects.go
  pkg/storage/mysql/mysql.go
  pkg/storage/mysql/mysql_test.go
  pkg/storage/postgres/postgres.go
  pkg/storage/postgres/postgres_test.go
  pkg/storage/sqlcommon/sqlcommon.go
Labels: performance

#2410 feat: shared iterator skeleton
  .config-schema.json
  cmd/run/flags.go
  cmd/run/run.go
  cmd/run/run_test.go
  internal/shared/shared.go
  pkg/server/config/cache_settings.go
  pkg/server/config/config.go
  pkg/server/server.go
  pkg/storage/storagewrappers/cached_datastore.go
  pkg/storage/storagewrappers/request.go
  pkg/storage/storagewrappers/request_test.go
  pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore.go
  pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore_test.go
  pkg/storage/storagewrappers/storagewrappersutil/key_utils.go
Labels: Skip-Changelog

#2428 feat: add recover log in cached iterator stop goroutine
  pkg/storage/storagewrappers/cached_datastore.go
  pkg/storage/storagewrappers/cached_datastore_test.go
Labels: Skip-Changelog

#2429 chore: move the API Method const to their own file
  internal/authz/authz.go
  internal/authz/authz_test.go
  internal/utils/apimethod/apimethod.go
  pkg/server/assertions.go
  pkg/server/authorization_models.go
  pkg/server/batch_check.go
  pkg/server/check.go
  pkg/server/expand.go
  pkg/server/list_objects.go
  pkg/server/list_users.go
  pkg/server/read.go
  pkg/server/read_changes.go
  pkg/server/server.go
  pkg/server/server_authz_test.go
  pkg/server/stores.go
  pkg/server/write.go
Labels: Skip-Changelog

#2438 fix: flaky iter cache test
  pkg/storage/storagewrappers/cached_datastore.go
  pkg/storage/storagewrappers/cached_datastore_test.go
Labels: Skip-Changelog

#2432 fix: panic handling in shadow resolver
  internal/graph/shadow_resolver.go
  internal/graph/shadow_resolver_test.go
Labels: Skip-Changelog

#2434 feat: make sqlite lazy
  pkg/storage/mysql/mysql.go
  pkg/storage/mysql/mysql_test.go
  pkg/storage/postgres/postgres.go
  pkg/storage/postgres/postgres_test.go
  pkg/storage/sqlcommon/sqlcommon.go
  pkg/storage/sqlite/sqlite.go
  pkg/storage/sqlite/tuple_iterator.go
Labels: Skip-Changelog

#2451 Revert "feat: make sqlite lazy"
  pkg/storage/mysql/mysql.go
  pkg/storage/mysql/mysql_test.go
  pkg/storage/postgres/postgres.go
  pkg/storage/postgres/postgres_test.go
  pkg/storage/sqlcommon/sqlcommon.go
  pkg/storage/sqlite/sqlite.go
  pkg/storage/sqlite/tuple_iterator.go
Labels: Skip-Changelog

#2450 fix: watch context when dispatch throttling
  CHANGELOG.md
  internal/throttler/throttler.go
Labels: bug

#2444 chore: add fatcontext linter
  .golangci.yaml
  pkg/server/commands/expand_test.go
  pkg/server/commands/list_objects_test.go
Labels: Skip-Changelog

#2447 chore: add copyloopvar linter
  .golangci.yaml
  cmd/run/run_test.go
  internal/checkutil/checkutil_test.go
  internal/graph/cached_resolver_test.go
  internal/graph/check_test.go
  pkg/server/commands/expand.go
  pkg/server/commands/listusers/list_users_rpc.go
  pkg/server/commands/listusers/list_users_rpc_test.go
  pkg/server/config/config_test.go
  pkg/server/test/list_objects.go
  pkg/tuple/tuple_test.go
  pkg/typesystem/typesystem_test.go
  tests/check/check.go
  tests/functional_test.go
  tests/listobjects/listobjects.go
  tests/listusers/listusers.go
Labels: Skip-Changelog

#2453 fix: refactor handlesqlerror and minor fixes
  pkg/server/server_test.go
  pkg/storage/mysql/mysql.go
  pkg/storage/mysql/mysql_test.go
  pkg/storage/postgres/postgres.go
  pkg/storage/postgres/postgres_test.go
  pkg/storage/sqlcommon/sqlcommon.go
  pkg/storage/sqlite/sqlite.go
  pkg/storage/sqlite/tuple_iterator.go
Labels: Skip-Changelog

#2458 fix: shared iterator should not store context cancelled error
  pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore.go
  pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore_test.go
  tests/check/check_test.go
  tests/tests.go
Labels: Skip-Changelog

#2459 feat: shared iterator measurement unique by method
  pkg/storage/storagewrappers/request.go
  pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore.go
Labels: Skip-Changelog

#2457 Revert "feat: add recover log in cached iterator stop goroutine (#2428)"
  CHANGELOG.md
  pkg/storage/storagewrappers/cached_datastore.go
  pkg/storage/storagewrappers/cached_datastore_test.go
Labels: Skip-Changelog

#2467 revert: fanin refactor with additional bounding
  internal/graph/check_fast_path.go
  internal/graph/object_providers.go
  internal/graph/object_providers_test.go
Labels: Skip-Changelog

#2463 chore: add recvcheck linter
  .golangci.yaml
  internal/condition/types/ipaddress.go
Labels: Skip-Changelog

#2464 chore: bump language repo dependency version
  go.mod
  go.sum
  pkg/typesystem/typesystem_test.go
Labels: Skip-Changelog
