Repository openfga/openfga, pull requests merged in 2025-01, with the labels that each got.

#2194 rework cache key hash generation
  internal/keys/hasher.go
  internal/keys/hasher_test.go
  pkg/storage/cache.go
  pkg/tuple/tuple.go
  pkg/tuple/tuple_test.go
Labels: refactor, Skip-Changelog

#2197 chore: introduce new ordered combined iterator
  pkg/storage/iterators.go
  pkg/storage/iterators_test.go
Labels: Skip-Changelog

#2201 test: add error test cases to the hasher Write* functions in the keys package
  internal/keys/hasher.go
  internal/keys/hasher_test.go
  pkg/tuple/tuple.go
  pkg/tuple/tuple_test.go
Labels: tests, Skip-Changelog

#2203 avoid mutating reference input
  internal/keys/hasher.go
Labels: refactor, Skip-Changelog

#2206 chore: remove dead cache key code
  internal/keys/hasher.go
  internal/keys/hasher_test.go
  internal/keys/keys.go
  internal/keys/keys_test.go
  pkg/storage/cache.go
  pkg/storage/cache_test.go
Labels: refactor, Skip-Changelog

#2207 chore: replace sprintf in cache code
  pkg/storage/cache.go
  pkg/storage/cache_test.go
Labels: refactor, Skip-Changelog

#2198 fix: iterator need to be flushed after invalidation
  internal/graph/storagewrapper.go
  internal/graph/storagewrapper_test.go
Labels: Skip-Changelog

#2209 docs: update changelog to prep for v1.8.4
  CHANGELOG.md
Labels: Skip-Changelog

#2199 chore: add debug message to cache controller
  internal/cachecontroller/cache_controller.go
  internal/cachecontroller/cache_controller_test.go
  internal/graph/cached_resolver.go
  internal/graph/storagewrapper.go
  internal/graph/storagewrapper_test.go
  internal/shared/shared.go
  pkg/server/commands/check_command.go
  pkg/server/commands/check_command_test.go
  pkg/server/server.go
  pkg/storage/storagewrappers/request.go
  pkg/storage/storagewrappers/request_test.go
Labels: Skip-Changelog

#2218 test: shuffle order of tuples when writing them
  pkg/server/test/check.go
  pkg/server/test/list_objects.go
  pkg/server/test/list_users.go
  pkg/storage/test/storage.go
Labels: Skip-Changelog

#2219 chore: move cached iterators & wrappers
  pkg/storage/storagewrappers/cached_iterators.go
  pkg/storage/storagewrappers/cached_iterators_test.go
  pkg/storage/storagewrappers/check_caching.go
  pkg/storage/storagewrappers/check_caching_test.go
  pkg/storage/storagewrappers/model_caching.go
  pkg/storage/storagewrappers/model_caching_test.go
  pkg/storage/storagewrappers/request.go
  pkg/storage/storagewrappers/request_test.go
Labels: Skip-Changelog

#2220 test: use storage wrapper in Check unit tests
  internal/graph/check_fast_path.go
  internal/graph/check_fast_path_test.go
  internal/graph/check_test.go
Labels: Skip-Changelog

#2193 perf: make computation of cache keys faster
  CHANGELOG.md
  internal/graph/cached_resolver.go
  internal/graph/cached_resolver_test.go
  internal/graph/resolve_check_request.go
  internal/graph/resolve_check_request_test.go
  pkg/server/commands/batch_check_command.go
  pkg/server/commands/check_command.go
  pkg/server/commands/check_command_test.go
  pkg/server/commands/list_objects_test.go
  pkg/server/server_test.go
  pkg/storage/cache.go
  pkg/storage/cache_test.go
  pkg/tuple/tuple.go
  pkg/tuple/tuple_test.go
Labels: refactor

#2212 chore: minor updates to code comments in cache controller
  internal/cachecontroller/cache_controller.go
  pkg/storage/storagewrappers/check_caching.go
Labels: Skip-Changelog

#2226 chore: move tuple iterators and mappers inside pkg/storage
  internal/graph/check.go
  internal/graph/check_fast_path.go
  internal/graph/check_fast_path_test.go
  internal/graph/check_test.go
  internal/mocks/mock_iterator.go
  pkg/storage/tuple_iterators.go
  pkg/storage/tuple_iterators_test.go
  pkg/storage/tuple_mappers.go
  pkg/storage/tuple_mappers_test.go
Labels: Skip-Changelog

#2221 test: move tests for Expand
  pkg/server/commands/expand.go
  pkg/server/commands/expand_test.go
  pkg/server/test/expand.go
  pkg/server/test/server.go
  pkg/typesystem/typesystem.go
Labels: Skip-Changelog

#2100 chore: remove unused `maxConcurrentReads` from LocalChecker
  internal/graph/check.go
  pkg/server/commands/list_objects_test.go
  pkg/server/test/list_objects.go
Labels: Skip-Changelog

#2235 refactor: return string instead of one-element string slice
  internal/cachecontroller/cache_controller.go
  internal/cachecontroller/cache_controller_test.go
  pkg/storage/cache.go
  pkg/storage/storagewrappers/check_caching.go
  pkg/storage/storagewrappers/check_caching_test.go
Labels: Skip-Changelog

#2232 chore: update language dependency
  go.mod
  go.sum
  pkg/typesystem/typesystem.go
  pkg/typesystem/typesystem_test.go
Labels: Skip-Changelog

#2238 perf: remove fmt.sprintf and just add strings
  pkg/tuple/tuple.go
Labels: Skip-Changelog

#2246 test: fix benchmark alarm firing due to randomness
  pkg/server/test/check.go
Labels: Skip-Changelog

#2248 chore: add perfsprint linter
  .golangci.yaml
  pkg/server/test/list_objects.go
  pkg/server/test/list_users.go
  tests/check/check.go
Labels: Skip-Changelog

#2239 refactor: move some functionality into iterator stream
  internal/graph/check_fast_path.go
  internal/graph/check_fast_path_test.go
  internal/graph/iterator/iterator_stream.go
  internal/graph/iterator/iterator_stream_test.go
Labels: Skip-Changelog

#2255 adding a remaining wildcard use case to the fast path, and including test
  pkg/typesystem/typesystem.go
  pkg/typesystem/typesystem_test.go
Labels: Skip-Changelog
