Repository openfga/openfga, pull requests merged in 2025-07, with the labels that each got.

#2545 fix: race condition in throttler test
  internal/throttler/throttler_test.go
Labels: bug, tests, Skip-Changelog

#2539 Log main and shadow ListObjects query latencies
  pkg/server/commands/list_objects_shadow.go
  pkg/server/commands/list_objects_shadow_test.go
Labels: Skip-Changelog

#2544 fix: shared iterator race and deadlock
  CHANGELOG.md
  pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore.go
  pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore_test.go
Labels: bug, performance

#2548 validate that shadow mode is executed when main context cancelled
  pkg/server/commands/list_objects_shadow_test.go
Labels: tests, Skip-Changelog

#2549 perf: create per datastore operation caches for shared iterators
  CHANGELOG.md
  pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore.go
  pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore_test.go
Labels: performance

#2550 fix: add shared iterator count decrement when the timer evicts the iterator
  pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore.go
  pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore_test.go
Labels: telemetry, Skip-Changelog

#2555 Update stack funcs to use values, not pointers
  internal/stack/stack.go
  internal/stack/stack_test.go
  pkg/server/commands/reverseexpand/reverse_expand.go
Labels: Skip-Changelog

#2552 chore: shared iterator benchmark cleanup
  pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore_test.go
Labels: tests, Skip-Changelog

#2561 fix data race around wait group in shared iterator
  pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore.go
Labels: bug, Skip-Changelog

#2562 chore: add datastore_query_count to shadow list objects logger
  pkg/server/commands/list_objects_shadow.go
  pkg/server/commands/list_objects_shadow_test.go
Labels: Skip-Changelog

#2568 short circuit iteratorsToUserset
  internal/graph/object_providers.go
  internal/graph/object_providers_test.go
Labels: Skip-Changelog

#2565 Fix migrate command logging options
  CHANGELOG.md
  cmd/migrate/flags.go
  cmd/migrate/migrate.go
  pkg/storage/migrate/migrate.go
Labels: codex

#2587 fix: removes isDuplicateQuery check from reverse_expand_weighted
  pkg/server/commands/reverseexpand/reverse_expand_weighted.go
Labels: Skip-Changelog

#2591 chore: add main query count to shadow list objects logging
  pkg/server/commands/list_objects_shadow.go
  pkg/server/commands/list_objects_shadow_test.go
Labels: Skip-Changelog
