Repository openfga/openfga, pull requests merged in 2025-08, with the labels that each got.

#2604 chore: dependencies update
  go.mod
  go.sum
Labels: Skip-Changelog

#2608 fix: support tuple iterator cache in integration tests
  assets/tests/consolidated_1_1_tests.yaml
  tests/check/check_test.go
Labels: tests, Skip-Changelog

#2610 chore: specify github-native as changelog generation to use
  .goreleaser.yaml
Labels: Skip-Changelog

#2611 chore: temporarily ignore test tags for testing
  .github/workflows/release.yaml
Labels: Skip-Changelog

#2618 Update changelog to prep for release `1.9.6`
  CHANGELOG.md
Labels: release

#2623 Delete SECURITY-INSIGHTS v1.0.0
  SECURITY-INSIGHTS.yml
Labels: Skip-Changelog

#2625 chore(ci): remove semgrep workflow
  .github/workflows/semgrep.yaml
Labels: Skip-Changelog

#2636 fix: don't specify an oidc audience when one is not configured
  CHANGELOG.md
  internal/authn/oidc/oidc.go
  internal/authn/oidc/oidc_test.go
Labels: bug

#2639 ci: update dependabot config
  .github/dependabot.yaml
Labels: dependencies

#2642 chore: refactor userset
  internal/checkutil/checkutil.go
  internal/graph/check.go
  internal/graph/default_resolver.go
  internal/graph/default_resolver_test.go
  internal/graph/recursive_resolver.go
  internal/graph/recursive_resolver_test.go
  internal/graph/weight_two_resolver.go
  internal/graph/weight_two_resolver_test.go
  pkg/typesystem/typesystem.go
  pkg/typesystem/typesystem_test.go
Labels: Skip-Changelog

#2584 chore: Benchmarks for ListObjects
  pkg/server/commands/list_objects_test.go
Labels: Skip-Changelog

#2657 chore: fix config schema
  .config-schema.json
Labels: Skip-Changelog

#2656 chore: remove noisy logger in reverse expand
  pkg/server/commands/reverseexpand/reverse_expand.go
Labels: Skip-Changelog

#2662 feat: duplicate writes (sqlite)
  pkg/storage/sqlite/sqlite.go
  pkg/storage/sqlite/sqlite_test.go
Labels: Skip-Changelog
